/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * This endpoint allows you to get a list of attribute options. Attribute options are paginated and sorted by code.
 * @summary Get list of attribute options
 */
export const getAttributesAttributeCodeOptionsParams = zod.object({
  "attribute_code": zod.string()
})

export const getAttributesAttributeCodeOptionsQueryLimitMax = 100;


export const getAttributesAttributeCodeOptionsQueryParams = zod.object({
  "page": zod.number().optional(),
  "limit": zod.number().min(1).max(getAttributesAttributeCodeOptionsQueryLimitMax).optional(),
  "with_count": zod.boolean().optional()
})

export const getAttributesAttributeCodeOptionsResponse = zod.object({
  "_links": zod.object({
  "first": zod.object({
  "href": zod.string().optional()
}).optional(),
  "next": zod.object({
  "href": zod.string().optional()
}).optional(),
  "previous": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "current_page": zod.number().optional()
}).and(zod.object({
  "_embedded": zod.object({
  "items": zod.array(zod.object({
  "_links": zod.object({
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional()
}).and(zod.object({
  "attribute": zod.string().optional(),
  "code": zod.string(),
  "labels": zod.object({
  "localeCode": zod.string().optional()
}).optional(),
  "sort_order": zod.number().optional()
}))).optional()
}).optional()
}))

/**
 * This endpoint allows you to update several attribute options at once.
 * @summary Update/create several attribute options
 */
export const patchAttributesAttributeCodeOptionsParams = zod.object({
  "attribute_code": zod.string()
})

export const patchAttributesAttributeCodeOptionsBody = zod.object({
  "attribute": zod.string().optional(),
  "code": zod.string(),
  "labels": zod.object({
  "localeCode": zod.string().optional()
}).optional(),
  "sort_order": zod.number().optional()
})

export const patchAttributesAttributeCodeOptionsResponse = zod.object({
  "code": zod.string().optional(),
  "identifier": zod.string().optional(),
  "line": zod.number().optional(),
  "message": zod.string().optional(),
  "status_code": zod.number().optional()
})

/**
 * This endpoint allows you to create a new attribute option.
 * @summary Create a new attribute option
 */
export const postAttributesAttributeCodeOptionsParams = zod.object({
  "attribute_code": zod.string()
})

export const postAttributesAttributeCodeOptionsBody = zod.object({
  "attribute": zod.string().optional(),
  "code": zod.string(),
  "labels": zod.object({
  "localeCode": zod.string().optional()
}).optional(),
  "sort_order": zod.number().optional()
})

/**
 * This endpoint allows you to get the information about a given attribute option.
 * @summary Get an attribute option
 */
export const getAttributesAttributeCodeOptionsCodeParams = zod.object({
  "attribute_code": zod.string(),
  "code": zod.string()
})

export const getAttributesAttributeCodeOptionsCodeResponse = zod.object({
  "attribute": zod.string().optional(),
  "code": zod.string(),
  "labels": zod.object({
  "localeCode": zod.string().optional()
}).optional(),
  "sort_order": zod.number().optional()
})

/**
 * This endpoint allows you to update a given attribute option. Know more about <a href="/documentation/update.html#update-behavior">Update behavior</a>. Note that if no attribute option exists for the given code, it creates it.
 * @summary Update/create an attribute option
 */
export const patchAttributesAttributeCodeOptionsCodeParams = zod.object({
  "attribute_code": zod.string(),
  "code": zod.string()
})

export const patchAttributesAttributeCodeOptionsCodeBody = zod.object({
  "attribute": zod.string().optional(),
  "code": zod.string(),
  "labels": zod.object({
  "localeCode": zod.string().optional()
}).optional(),
  "sort_order": zod.number().optional()
})

