/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  GetAssetCategories200One,
  GetAssetCategoriesCode200,
  PatchAssetCategories200One
} from '../../model'

export const getGetAssetCategoriesResponseMock = (): GetAssetCategories200One => ({_links: faker.helpers.arrayElement([{first: faker.helpers.arrayElement([{href: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined]), next: faker.helpers.arrayElement([{href: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined]), previous: faker.helpers.arrayElement([{href: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined]), self: faker.helpers.arrayElement([{href: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined])}, undefined]), current_page: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]),..._embedded: faker.helpers.arrayElement([{items: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({_links: faker.helpers.arrayElement([{self: faker.helpers.arrayElement([{href: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined])}, undefined]),code: faker.string.alpha(20), labels: faker.helpers.arrayElement([{localeCode: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined]), parent: faker.helpers.arrayElement([faker.string.alpha(20), undefined])})), undefined])}, undefined])})

export const getPatchAssetCategoriesResponseMock = (overrideResponse: Partial< PatchAssetCategories200One > = {}): PatchAssetCategories200One => ({code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), identifier: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), line: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), status_code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), ...overrideResponse})

export const getGetAssetCategoriesCodeResponseMock = (): GetAssetCategoriesCode200 => ({"code":"front_views","labels":{"en_US":"Front views","fr_FR":"Vues de face"},"parent":"pictures"})


export const getGetAssetCategoriesMockHandler = (overrideResponse?: GetAssetCategories200One | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetAssetCategories200One> | GetAssetCategories200One)) => {
  return http.get('*/api/rest/v1/asset-categories', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetAssetCategoriesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPatchAssetCategoriesMockHandler = (overrideResponse?: PatchAssetCategories200One | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<PatchAssetCategories200One> | PatchAssetCategories200One)) => {
  return http.patch('*/api/rest/v1/asset-categories', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPatchAssetCategoriesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPostAssetCategoriesMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void)) => {
  return http.post('*/api/rest/v1/asset-categories', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 201,
        
      })
  })
}

export const getGetAssetCategoriesCodeMockHandler = (overrideResponse?: GetAssetCategoriesCode200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetAssetCategoriesCode200> | GetAssetCategoriesCode200)) => {
  return http.get('*/api/rest/v1/asset-categories/:code', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetAssetCategoriesCodeResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPatchAssetCategoriesCodeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void)) => {
  return http.patch('*/api/rest/v1/asset-categories/:code', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 201,
        
      })
  })
}
export const getPamAssetCategoryMock = () => [
  getGetAssetCategoriesMockHandler(),
  getPatchAssetCategoriesMockHandler(),
  getPostAssetCategoriesMockHandler(),
  getGetAssetCategoriesCodeMockHandler(),
  getPatchAssetCategoriesCodeMockHandler()
]
