/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * This endpoint allows you to get a list of PAM assets. PAM assets are paginated.
 * @summary Get list of PAM assets
 */
export const getPamAssetsQueryLimitMax = 100;


export const getPamAssetsQueryParams = zod.object({
  "pagination_type": zod.enum(['page', 'search_after']).optional(),
  "page": zod.number().optional(),
  "search_after": zod.string().optional(),
  "limit": zod.number().min(1).max(getPamAssetsQueryLimitMax).optional(),
  "with_count": zod.boolean().optional()
})

export const getPamAssetsResponse = zod.object({
  "_links": zod.object({
  "first": zod.object({
  "href": zod.string().optional()
}).optional(),
  "next": zod.object({
  "href": zod.string().optional()
}).optional(),
  "previous": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "current_page": zod.number().optional()
}).and(zod.object({
  "_embedded": zod.object({
  "items": zod.array(zod.object({
  "_links": zod.object({
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional()
}).and(zod.object({
  "categories": zod.array(zod.string()).optional(),
  "code": zod.string(),
  "description": zod.string().optional(),
  "end_of_use": zod.string().optional(),
  "localizable": zod.boolean().optional(),
  "reference_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional()
})).optional(),
  "tags": zod.array(zod.string()).optional(),
  "variation_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional(),
  "scope": zod.string().optional()
})).optional()
}))).optional()
}).optional()
}))

/**
 * This endpoint allows you to update several PAM assets at once.
 * @summary Update/create several PAM assets
 */
export const patchPamAssetsBody = zod.object({
  "categories": zod.array(zod.string()).optional(),
  "code": zod.string(),
  "description": zod.string().optional(),
  "end_of_use": zod.string().optional(),
  "localizable": zod.boolean().optional(),
  "reference_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional()
})).optional(),
  "tags": zod.array(zod.string()).optional(),
  "variation_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional(),
  "scope": zod.string().optional()
})).optional()
})

export const patchPamAssetsResponse = zod.object({
  "code": zod.string().optional(),
  "identifier": zod.string().optional(),
  "line": zod.number().optional(),
  "message": zod.string().optional(),
  "status_code": zod.number().optional()
})

/**
 * This endpoint allows you to create a new PAM asset.
 * @summary Create a new PAM asset
 */
export const postPamAssetsBody = zod.object({
  "categories": zod.array(zod.string()).optional(),
  "code": zod.string(),
  "description": zod.string().optional(),
  "end_of_use": zod.string().optional(),
  "localizable": zod.boolean().optional(),
  "reference_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional()
})).optional(),
  "tags": zod.array(zod.string()).optional(),
  "variation_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional(),
  "scope": zod.string().optional()
})).optional()
})

/**
 * This endpoint allows you to get the information about a given PAM asset.
 * @summary Get a PAM asset
 */
export const getPamAssetsCodeParams = zod.object({
  "code": zod.string()
})

export const getPamAssetsCodeResponse = zod.object({
  "categories": zod.array(zod.string()).optional(),
  "code": zod.string(),
  "description": zod.string().optional(),
  "end_of_use": zod.string().optional(),
  "localizable": zod.boolean().optional(),
  "reference_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional()
})).optional(),
  "tags": zod.array(zod.string()).optional(),
  "variation_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional(),
  "scope": zod.string().optional()
})).optional()
})

/**
 * This endpoint allows you to update a given PAM asset. Know more about <a href="/documentation/update.html#update-behavior">Update behavior</a>. Note that if no asset exists for the given code, it creates it.
 * @summary Update/create a PAM asset
 */
export const patchPamAssetsCodeParams = zod.object({
  "code": zod.string()
})

export const patchPamAssetsCodeBody = zod.object({
  "categories": zod.array(zod.string()).optional(),
  "code": zod.string(),
  "description": zod.string().optional(),
  "end_of_use": zod.string().optional(),
  "localizable": zod.boolean().optional(),
  "reference_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional()
})).optional(),
  "tags": zod.array(zod.string()).optional(),
  "variation_files": zod.array(zod.object({
  "_link": zod.object({
  "download": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "code": zod.string().optional(),
  "locale": zod.string().optional(),
  "scope": zod.string().optional()
})).optional()
})

