/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * This endpoint allows you to get a list of currencies. Currencies are paginated and sorted by code.
 * @summary Get a list of currencies
 */
export const currenciesGetListQueryLimitMax = 100;


export const currenciesGetListQueryParams = zod.object({
  "page": zod.number().optional(),
  "limit": zod.number().min(1).max(currenciesGetListQueryLimitMax).optional(),
  "with_count": zod.boolean().optional()
})

export const currenciesGetListResponse = zod.object({
  "_links": zod.object({
  "first": zod.object({
  "href": zod.string().optional()
}).optional(),
  "next": zod.object({
  "href": zod.string().optional()
}).optional(),
  "previous": zod.object({
  "href": zod.string().optional()
}).optional(),
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional(),
  "current_page": zod.number().optional()
}).and(zod.object({
  "_embedded": zod.object({
  "items": zod.array(zod.object({
  "_links": zod.object({
  "self": zod.object({
  "href": zod.string().optional()
}).optional()
}).optional()
}).and(zod.object({
  "code": zod.string(),
  "enabled": zod.boolean().optional()
}))).optional()
}).optional()
}))

/**
 * This endpoint allows you to get the information about a given currency.
 * @summary Get a currency
 */
export const currenciesGetParams = zod.object({
  "code": zod.string()
})

export const currenciesGetResponse = zod.object({
  "code": zod.string(),
  "enabled": zod.boolean().optional()
})

