/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _AttributeGroupsGetList200OneAllOfLinksFirst } from './_attributeGroupsGetList200OneAllOfLinksFirst';
import type { _AttributeGroupsGetList200OneAllOfLinksNext } from './_attributeGroupsGetList200OneAllOfLinksNext';
import type { _AttributeGroupsGetList200OneAllOfLinksPrevious } from './_attributeGroupsGetList200OneAllOfLinksPrevious';
import type { _AttributeGroupsGetList200OneAllOfLinksSelf } from './_attributeGroupsGetList200OneAllOfLinksSelf';

export type _AttributeGroupsGetList200OneAllOfLinks = {
  first?: _AttributeGroupsGetList200OneAllOfLinksFirst;
  next?: _AttributeGroupsGetList200OneAllOfLinksNext;
  previous?: _AttributeGroupsGetList200OneAllOfLinksPrevious;
  self?: _AttributeGroupsGetList200OneAllOfLinksSelf;
};
