/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _AttributeGroupsGetList200OneAllOfSevenEmbeddedItemsItemAllOfFourLabels } from './_attributeGroupsGetList200OneAllOfSevenEmbeddedItemsItemAllOfFourLabels';

export type _AttributeGroupsGetList200OneAllOfSevenEmbeddedItemsItemAllOfFour = {
  /** Attribute codes that compose the attribute group */
  attributes?: string[];
  /** Attribute group code */
  code: string;
  /** Attribute group labels for each locale */
  labels?: _AttributeGroupsGetList200OneAllOfSevenEmbeddedItemsItemAllOfFourLabels;
  /** Attribute group order among other attribute groups */
  sort_order?: number;
};
