/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _CurrenciesGetList200OneAllOfSevenEmbeddedItemsItem } from './_currenciesGetList200OneAllOfSevenEmbeddedItemsItem';

export type _CurrenciesGetList200OneAllOfSevenEmbedded = {
  items?: _CurrenciesGetList200OneAllOfSevenEmbeddedItemsItem[];
};
