/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _CurrencyListAllOfLinksSelf } from './_currencyListAllOfLinksSelf';

export type _CurrencyListAllOfLinks = {
  self?: _CurrencyListAllOfLinksSelf;
};
