/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _DeprecatedAssetReferenceFilesItemLinkDownload } from './_deprecatedAssetReferenceFilesItemLinkDownload';
import type { _DeprecatedAssetReferenceFilesItemLinkSelf } from './_deprecatedAssetReferenceFilesItemLinkSelf';

/**
 * Links to get and download the reference file
 */
export type _DeprecatedAssetReferenceFilesItemLink = {
  download?: _DeprecatedAssetReferenceFilesItemLinkDownload;
  self?: _DeprecatedAssetReferenceFilesItemLinkSelf;
};
