/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetReferenceEntityRecords200OneAllOfLinksFirst } from './_getReferenceEntityRecords200OneAllOfLinksFirst';
import type { _GetReferenceEntityRecords200OneAllOfLinksNext } from './_getReferenceEntityRecords200OneAllOfLinksNext';
import type { _GetReferenceEntityRecords200OneAllOfLinksSelf } from './_getReferenceEntityRecords200OneAllOfLinksSelf';

export type _GetReferenceEntityRecords200OneAllOfLinks = {
  first?: _GetReferenceEntityRecords200OneAllOfLinksFirst;
  next?: _GetReferenceEntityRecords200OneAllOfLinksNext;
  self?: _GetReferenceEntityRecords200OneAllOfLinksSelf;
};
