/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAttributes200OneAllOfSevenEmbeddedItemsItemAllOfLinks } from './_getAttributes200OneAllOfSevenEmbeddedItemsItemAllOfLinks';

export type _GetAttributes200OneAllOfSevenEmbeddedItemsItemAllOf = {
  _links?: _GetAttributes200OneAllOfSevenEmbeddedItemsItemAllOfLinks;
};
