/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAssets200OneAllOfSixEmbeddedItemsItem } from './_getAssets200OneAllOfSixEmbeddedItemsItem';

export type _GetAssets200OneAllOfSixEmbedded = {
  _items?: _GetAssets200OneAllOfSixEmbeddedItemsItem[];
};
