/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetPublishedProducts200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItemData } from './_getPublishedProducts200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItemData';

export type _GetPublishedProducts200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItem = {
  /** <a href='api-reference.html#Productuuid'>Product</a> value */
  data?: _GetPublishedProducts200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItemData;
  /** <a href='api-reference.html#Locale'>Locale</a> code of the product value */
  locale?: string;
  /** <a href='api-reference.html#Channel'>Channel</a> code of the product value */
  scope?: string;
};
