/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProductsUuid200AllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItem } from './_getProductsUuid200AllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItem';

/**
 * Product attributes values, see <a href='/concepts/products.html#focus-on-the-product-values'>Product values</a> section for more details
 */
export type _GetProductsUuid200AllOfSevenEmbeddedItemsItemAllOfFourValues = {
  attributeCode?: _GetProductsUuid200AllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeItem[];
};
