/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetCategories200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeAttributeUuidChannelCodeLocaleCodeItem } from './_getCategories200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeAttributeUuidChannelCodeLocaleCodeItem';

/**
 * Attribute values
 */
export type _GetCategories200OneAllOfSevenEmbeddedItemsItemAllOfFourValues = {
  'attributeCode|attributeUuid|channelCode|localeCode'?: _GetCategories200OneAllOfSevenEmbeddedItemsItemAllOfFourValuesAttributeCodeAttributeUuidChannelCodeLocaleCodeItem[];
};
