/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAssetFamilies200OneAllOfLinksFirst } from './_getAssetFamilies200OneAllOfLinksFirst';
import type { _GetAssetFamilies200OneAllOfLinksNext } from './_getAssetFamilies200OneAllOfLinksNext';
import type { _GetAssetFamilies200OneAllOfLinksSelf } from './_getAssetFamilies200OneAllOfLinksSelf';

export type _GetAssetFamilies200OneAllOfLinks = {
  first?: _GetAssetFamilies200OneAllOfLinksFirst;
  next?: _GetAssetFamilies200OneAllOfLinksNext;
  self?: _GetAssetFamilies200OneAllOfLinksSelf;
};
