/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetFamiliesFamilyCodeVariants200OneAllOfLinksFirst } from './_getFamiliesFamilyCodeVariants200OneAllOfLinksFirst';
import type { _GetFamiliesFamilyCodeVariants200OneAllOfLinksNext } from './_getFamiliesFamilyCodeVariants200OneAllOfLinksNext';
import type { _GetFamiliesFamilyCodeVariants200OneAllOfLinksPrevious } from './_getFamiliesFamilyCodeVariants200OneAllOfLinksPrevious';
import type { _GetFamiliesFamilyCodeVariants200OneAllOfLinksSelf } from './_getFamiliesFamilyCodeVariants200OneAllOfLinksSelf';

export type _GetFamiliesFamilyCodeVariants200OneAllOfLinks = {
  first?: _GetFamiliesFamilyCodeVariants200OneAllOfLinksFirst;
  next?: _GetFamiliesFamilyCodeVariants200OneAllOfLinksNext;
  previous?: _GetFamiliesFamilyCodeVariants200OneAllOfLinksPrevious;
  self?: _GetFamiliesFamilyCodeVariants200OneAllOfLinksSelf;
};
