/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProductModels200OneAllOfSevenEmbeddedItemsItemAllOf } from './_getProductModels200OneAllOfSevenEmbeddedItemsItemAllOf';
import type { _GetProductModels200OneAllOfSevenEmbeddedItemsItemAllOfFour } from './_getProductModels200OneAllOfSevenEmbeddedItemsItemAllOfFour';

export type _GetProductModels200OneAllOfSevenEmbeddedItemsItem = _GetProductModels200OneAllOfSevenEmbeddedItemsItemAllOf & _GetProductModels200OneAllOfSevenEmbeddedItemsItemAllOfFour;
