/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinksImageDownload } from './_getReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinksImageDownload';
import type { _GetReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinksSelf } from './_getReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinksSelf';

export type _GetReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinks = {
  image_download?: _GetReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinksImageDownload;
  self?: _GetReferenceEntities200OneAllOfSixEmbeddedItemsItemAllOfLinksSelf;
};
