/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetPamAssets200OneAllOfLinksFirst } from './_getPamAssets200OneAllOfLinksFirst';
import type { _GetPamAssets200OneAllOfLinksNext } from './_getPamAssets200OneAllOfLinksNext';
import type { _GetPamAssets200OneAllOfLinksPrevious } from './_getPamAssets200OneAllOfLinksPrevious';
import type { _GetPamAssets200OneAllOfLinksSelf } from './_getPamAssets200OneAllOfLinksSelf';

export type _GetPamAssets200OneAllOfLinks = {
  first?: _GetPamAssets200OneAllOfLinksFirst;
  next?: _GetPamAssets200OneAllOfLinksNext;
  previous?: _GetPamAssets200OneAllOfLinksPrevious;
  self?: _GetPamAssets200OneAllOfLinksSelf;
};
