/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetMediaFiles200OneAllOfLinksFirst } from './_getMediaFiles200OneAllOfLinksFirst';
import type { _GetMediaFiles200OneAllOfLinksNext } from './_getMediaFiles200OneAllOfLinksNext';
import type { _GetMediaFiles200OneAllOfLinksPrevious } from './_getMediaFiles200OneAllOfLinksPrevious';
import type { _GetMediaFiles200OneAllOfLinksSelf } from './_getMediaFiles200OneAllOfLinksSelf';

export type _GetMediaFiles200OneAllOfLinks = {
  first?: _GetMediaFiles200OneAllOfLinksFirst;
  next?: _GetMediaFiles200OneAllOfLinksNext;
  previous?: _GetMediaFiles200OneAllOfLinksPrevious;
  self?: _GetMediaFiles200OneAllOfLinksSelf;
};
