/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

export type _GetAssetTags200OneAllOfSevenEmbeddedItemsItemAllOfFour = {
  /** PAM asset tag code */
  code: string;
};
