/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProducts200AllOfSevenEmbeddedItemsItem } from './_getProducts200AllOfSevenEmbeddedItemsItem';

export type _GetProducts200AllOfSevenEmbedded = {
  items?: _GetProducts200AllOfSevenEmbeddedItemsItem[];
};
