/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProducts200AllOfSevenEmbeddedItemsItemAllOfFourAssociationsAssociationTypeCode } from './_getProducts200AllOfSevenEmbeddedItemsItemAllOfFourAssociationsAssociationTypeCode';

/**
 * Several associations related to groups, product models and/or other products, grouped by association types
 */
export type _GetProducts200AllOfSevenEmbeddedItemsItemAllOfFourAssociations = {
  associationTypeCode?: _GetProducts200AllOfSevenEmbeddedItemsItemAllOfFourAssociationsAssociationTypeCode;
};
