/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAppCatalogs200AllOfSevenEmbeddedItemsItemAllOf } from './_getAppCatalogs200AllOfSevenEmbeddedItemsItemAllOf';
import type { _GetAppCatalogs200AllOfSevenEmbeddedItemsItemAllOfFour } from './_getAppCatalogs200AllOfSevenEmbeddedItemsItemAllOfFour';

export type _GetAppCatalogs200AllOfSevenEmbeddedItemsItem = _GetAppCatalogs200AllOfSevenEmbeddedItemsItemAllOf & _GetAppCatalogs200AllOfSevenEmbeddedItemsItemAllOfFour;
