/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetFamilies200OneAllOfSevenEmbeddedItemsItemAllOf } from './_getFamilies200OneAllOfSevenEmbeddedItemsItemAllOf';
import type { _GetFamilies200OneAllOfSevenEmbeddedItemsItemAllOfFour } from './_getFamilies200OneAllOfSevenEmbeddedItemsItemAllOfFour';

export type _GetFamilies200OneAllOfSevenEmbeddedItemsItem = _GetFamilies200OneAllOfSevenEmbeddedItemsItemAllOf & _GetFamilies200OneAllOfSevenEmbeddedItemsItemAllOfFour;
