/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLinkDownload } from './_getPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLinkDownload';
import type { _GetPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLinkSelf } from './_getPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLinkSelf';

/**
 * Links to get and download the reference file
 */
export type _GetPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLink = {
  download?: _GetPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLinkDownload;
  self?: _GetPamAssets200OneAllOfSevenEmbeddedItemsItemAllOfFourReferenceFilesItemLinkSelf;
};
