/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProductsUuid200AllOfSevenEmbeddedItemsItemAllOfLinksSelf } from './_getProductsUuid200AllOfSevenEmbeddedItemsItemAllOfLinksSelf';

export type _GetProductsUuid200AllOfSevenEmbeddedItemsItemAllOfLinks = {
  self?: _GetProductsUuid200AllOfSevenEmbeddedItemsItemAllOfLinksSelf;
};
