/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinksDownload } from './_getMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinksDownload';
import type { _GetMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinksSelf } from './_getMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinksSelf';

export type _GetMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinks = {
  download?: _GetMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinksDownload;
  self?: _GetMediaFiles200OneAllOfSevenEmbeddedItemsItemAllOfLinksSelf;
};
