/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetCategories200OneAllOfSevenEmbeddedItemsItemAllOfLinks } from './_getCategories200OneAllOfSevenEmbeddedItemsItemAllOfLinks';

export type _GetCategories200OneAllOfSevenEmbeddedItemsItemAllOf = {
  _links?: _GetCategories200OneAllOfSevenEmbeddedItemsItemAllOfLinks;
};
