/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAppCatalogs200AllOfLinksFirst } from './_getAppCatalogs200AllOfLinksFirst';
import type { _GetAppCatalogs200AllOfLinksNext } from './_getAppCatalogs200AllOfLinksNext';
import type { _GetAppCatalogs200AllOfLinksPrevious } from './_getAppCatalogs200AllOfLinksPrevious';
import type { _GetAppCatalogs200AllOfLinksSelf } from './_getAppCatalogs200AllOfLinksSelf';

export type _GetAppCatalogs200AllOfLinks = {
  first?: _GetAppCatalogs200AllOfLinksFirst;
  next?: _GetAppCatalogs200AllOfLinksNext;
  previous?: _GetAppCatalogs200AllOfLinksPrevious;
  self?: _GetAppCatalogs200AllOfLinksSelf;
};
