/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _MeasureFamiliesGetList200OneAllOfSevenEmbeddedItemsItemAllOfLinks } from './_measureFamiliesGetList200OneAllOfSevenEmbeddedItemsItemAllOfLinks';

export type _MeasureFamiliesGetList200OneAllOfSevenEmbeddedItemsItemAllOf = {
  _links?: _MeasureFamiliesGetList200OneAllOfSevenEmbeddedItemsItemAllOfLinks;
};
