/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _MeasureFamiliesGetList200OneAllOfSevenEmbeddedItemsItem } from './_measureFamiliesGetList200OneAllOfSevenEmbeddedItemsItem';

export type _MeasureFamiliesGetList200OneAllOfSevenEmbedded = {
  items?: _MeasureFamiliesGetList200OneAllOfSevenEmbeddedItemsItem[];
};
