/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _MeasureFamiliesGetList200OneAllOfLinksFirst } from './_measureFamiliesGetList200OneAllOfLinksFirst';
import type { _MeasureFamiliesGetList200OneAllOfLinksNext } from './_measureFamiliesGetList200OneAllOfLinksNext';
import type { _MeasureFamiliesGetList200OneAllOfLinksPrevious } from './_measureFamiliesGetList200OneAllOfLinksPrevious';
import type { _MeasureFamiliesGetList200OneAllOfLinksSelf } from './_measureFamiliesGetList200OneAllOfLinksSelf';

export type _MeasureFamiliesGetList200OneAllOfLinks = {
  first?: _MeasureFamiliesGetList200OneAllOfLinksFirst;
  next?: _MeasureFamiliesGetList200OneAllOfLinksNext;
  previous?: _MeasureFamiliesGetList200OneAllOfLinksPrevious;
  self?: _MeasureFamiliesGetList200OneAllOfLinksSelf;
};
