/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _MediaFileItemListLinksDownload } from './_mediaFileItemListLinksDownload';
import type { _MediaFileItemListLinksSelf } from './_mediaFileItemListLinksSelf';

export type _MediaFileItemListLinks = {
  download?: _MediaFileItemListLinksDownload;
  self?: _MediaFileItemListLinksSelf;
};
