/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _PatchPamAssetsBodyVariationFilesItemLinkDownload } from './_patchPamAssetsBodyVariationFilesItemLinkDownload';
import type { _PatchPamAssetsBodyVariationFilesItemLinkSelf } from './_patchPamAssetsBodyVariationFilesItemLinkSelf';

/**
 * Links to get and download the variation file
 */
export type _PatchPamAssetsBodyVariationFilesItemLink = {
  download?: _PatchPamAssetsBodyVariationFilesItemLinkDownload;
  self?: _PatchPamAssetsBodyVariationFilesItemLinkSelf;
};
