/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _PostPamAssetsBodyVariationFilesItemLinkDownload } from './_postPamAssetsBodyVariationFilesItemLinkDownload';
import type { _PostPamAssetsBodyVariationFilesItemLinkSelf } from './_postPamAssetsBodyVariationFilesItemLinkSelf';

/**
 * Links to get and download the variation file
 */
export type _PostPamAssetsBodyVariationFilesItemLink = {
  download?: _PostPamAssetsBodyVariationFilesItemLinkDownload;
  self?: _PostPamAssetsBodyVariationFilesItemLinkSelf;
};
