/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _ReferenceEntityItemListLinksImageDownload } from './_referenceEntityItemListLinksImageDownload';
import type { _ReferenceEntityItemListLinksSelf } from './_referenceEntityItemListLinksSelf';

export type _ReferenceEntityItemListLinks = {
  image_download?: _ReferenceEntityItemListLinksImageDownload;
  self?: _ReferenceEntityItemListLinksSelf;
};
