/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _SearchAfterPaginationLinksFirst } from './_searchAfterPaginationLinksFirst';
import type { _SearchAfterPaginationLinksNext } from './_searchAfterPaginationLinksNext';
import type { _SearchAfterPaginationLinksSelf } from './_searchAfterPaginationLinksSelf';

export type _SearchAfterPaginationLinks = {
  first?: _SearchAfterPaginationLinksFirst;
  next?: _SearchAfterPaginationLinksNext;
  self?: _SearchAfterPaginationLinksSelf;
};
