/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { AttributeListAllOf } from './attributeListAllOf';
import type { AttributeListAllOfFour } from './attributeListAllOfFour';

export type AttributeList = AttributeListAllOf & AttributeListAllOfFour;
