/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { AttributeOptionListAllOf } from './attributeOptionListAllOf';
import type { AttributeOptionListAllOfFour } from './attributeOptionListAllOfFour';

export type AttributeOptionList = AttributeOptionListAllOf & AttributeOptionListAllOfFour;
