/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _CurrenciesGetList200OneAllOfSevenEmbedded } from './_currenciesGetList200OneAllOfSevenEmbedded';

export type CurrenciesGetList200OneAllOfSeven = {
  _embedded?: _CurrenciesGetList200OneAllOfSevenEmbedded;
};
