/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { DeprecatedAssetCategoryListAllOf } from './deprecatedAssetCategoryListAllOf';
import type { DeprecatedAssetCategoryListAllOfFour } from './deprecatedAssetCategoryListAllOfFour';

export type DeprecatedAssetCategoryList = DeprecatedAssetCategoryListAllOf & DeprecatedAssetCategoryListAllOfFour;
