/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssetFamilyCode200TransformationsItemOperationsParameters } from './getAssetFamilyCode200TransformationsItemOperationsParameters';

/**
 * The transformations that should be applied to your source file to generate the target file. More details <a href='/concepts/asset-manager.html#transformation-operations'>here</a>.
 */
export type GetAssetFamilyCode200TransformationsItemOperations = {
  parameters?: GetAssetFamilyCode200TransformationsItemOperationsParameters;
  type?: string;
};
