/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The string on which the naming convention should be applied. More details <a href='/concepts/asset-manager.html#source'>here</a>.
 */
export type GetAssetFamilyCode200NamingConventionSource = { [key: string]: unknown };
