/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * For the `media_link` attribute type, it is the type of the media behind the url, to allow its preview in the PIM. For the `media_file` attribute type, it is the type of the file.
 */
export type GetAssetFamilyAttributesCode200MediaType = typeof GetAssetFamilyAttributesCode200MediaType[keyof typeof GetAssetFamilyAttributesCode200MediaType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAssetFamilyAttributesCode200MediaType = {
  image: 'image',
  pdf: 'pdf',
  youtube: 'youtube',
  vimeo: 'vimeo',
  other: 'other',
} as const;
