/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAttributes200OneAllOf } from './getAttributes200OneAllOf';
import type { GetAttributes200OneAllOfSeven } from './getAttributes200OneAllOfSeven';

export type GetAttributes200One = GetAttributes200OneAllOf & GetAttributes200OneAllOfSeven;
