/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAppCatalogs200AllOf } from './getAppCatalogs200AllOf';
import type { GetAppCatalogs200AllOfSeven } from './getAppCatalogs200AllOfSeven';

export type GetAppCatalogs200 = GetAppCatalogs200AllOf & GetAppCatalogs200AllOfSeven;
