/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssetFamilies200OneAllOf } from './getAssetFamilies200OneAllOf';
import type { GetAssetFamilies200OneAllOfSix } from './getAssetFamilies200OneAllOfSix';

export type GetAssetFamilies200One = GetAssetFamilies200OneAllOf & GetAssetFamilies200OneAllOfSix;
