/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAttributesAttributeCodeOptions200OneAllOfSevenEmbedded } from './_getAttributesAttributeCodeOptions200OneAllOfSevenEmbedded';

export type GetAttributesAttributeCodeOptions200OneAllOfSeven = {
  _embedded?: _GetAttributesAttributeCodeOptions200OneAllOfSevenEmbedded;
};
