/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssets200OneAllOf } from './getAssets200OneAllOf';
import type { GetAssets200OneAllOfSix } from './getAssets200OneAllOfSix';

export type GetAssets200One = GetAssets200OneAllOf & GetAssets200OneAllOfSix;
