/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAppCatalogProducts200AllOf } from './getAppCatalogProducts200AllOf';
import type { GetAppCatalogProducts200AllOfSix } from './getAppCatalogProducts200AllOfSix';

export type GetAppCatalogProducts200 = GetAppCatalogProducts200AllOf & GetAppCatalogProducts200AllOfSix;
