/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssetFamilyAttributesAttributeCodeOptions200ItemLabels } from './getAssetFamilyAttributesAttributeCodeOptions200ItemLabels';

export type GetAssetFamilyAttributesAttributeCodeOptions200Item = {
  /** Attribute's option code */
  code: string;
  /** Attribute labels for each locale */
  labels?: GetAssetFamilyAttributesAttributeCodeOptions200ItemLabels;
};
