/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAssetFamilies200OneAllOfSixEmbedded } from './_getAssetFamilies200OneAllOfSixEmbedded';

export type GetAssetFamilies200OneAllOfSix = {
  _embedded?: _GetAssetFamilies200OneAllOfSixEmbedded;
};
