/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetAttributesAttributeCodeOptions200OneAllOfLinks } from './_getAttributesAttributeCodeOptions200OneAllOfLinks';

export type GetAttributesAttributeCodeOptions200OneAllOf = {
  _links?: _GetAttributesAttributeCodeOptions200OneAllOfLinks;
  /** Current page number */
  current_page?: number;
};
