/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

export type GetAttributesCodeParams = {
/**
 * Return the options of 'select' column types (of a table attribute) in the response. (Only available since the 7.0 version)
 */
with_table_select_options?: boolean;
};
