/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Endpoint to get the authentication token
 */
export type GetEndpoints200OneAuthentication = { [key: string]: unknown };
