/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFamiliesFamilyCodeVariants200OneAllOf } from './getFamiliesFamilyCodeVariants200OneAllOf';
import type { GetFamiliesFamilyCodeVariants200OneAllOfSeven } from './getFamiliesFamilyCodeVariants200OneAllOfSeven';

export type GetFamiliesFamilyCodeVariants200One = GetFamiliesFamilyCodeVariants200OneAllOf & GetFamiliesFamilyCodeVariants200OneAllOfSeven;
