/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetLocales200OneAllOfLinks } from './_getLocales200OneAllOfLinks';

export type GetLocales200OneAllOf = {
  _links?: _GetLocales200OneAllOfLinks;
  /** Current page number */
  current_page?: number;
};
