/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductsCode200AssociationsAssociationTypeCode } from './getProductsCode200AssociationsAssociationTypeCode';

/**
 * Several associations related to groups, product models and/or other products, grouped by association types
 */
export type GetProductsCode200Associations = {
  associationTypeCode?: GetProductsCode200AssociationsAssociationTypeCode;
};
