/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProductModels200OneAllOfLinks } from './_getProductModels200OneAllOfLinks';

export type GetProductModels200OneAllOf = {
  _links?: _GetProductModels200OneAllOfLinks;
  /** Current page number */
  current_page?: number;
};
