/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPublishedProductsCode200AssociationsAssociationTypeCode } from './getPublishedProductsCode200AssociationsAssociationTypeCode';

/**
 * Several associations related to groups and/or other published products, grouped by association types
 */
export type GetPublishedProductsCode200Associations = {
  associationTypeCode?: GetPublishedProductsCode200AssociationsAssociationTypeCode;
};
