/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductsCode200ValuesAttributeCodeItem } from './getProductsCode200ValuesAttributeCodeItem';

/**
 * Product attributes values, see <a href='/concepts/products.html#focus-on-the-product-values'>Product values</a> section for more details
 */
export type GetProductsCode200Values = {
  attributeCode?: GetProductsCode200ValuesAttributeCodeItem[];
};
