/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetProductsUuid200AllOf } from './getProductsUuid200AllOf';
import type { GetProductsUuid200AllOfSeven } from './getProductsUuid200AllOfSeven';

export type GetProductsUuid200 = GetProductsUuid200AllOf & GetProductsUuid200AllOfSeven;
