/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetProducts200AllOfSevenEmbedded } from './_getProducts200AllOfSevenEmbedded';

export type GetProducts200AllOfSeven = {
  _embedded?: _GetProducts200AllOfSevenEmbedded;
};
