/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { GetReferenceEntityRecords200OneAllOf } from './getReferenceEntityRecords200OneAllOf';
import type { GetReferenceEntityRecords200OneAllOfSix } from './getReferenceEntityRecords200OneAllOfSix';

export type GetReferenceEntityRecords200One = GetReferenceEntityRecords200OneAllOf & GetReferenceEntityRecords200OneAllOfSix;
