/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _GetReferenceEntityRecords200OneAllOfLinks } from './_getReferenceEntityRecords200OneAllOfLinks';

export type GetReferenceEntityRecords200OneAllOf = {
  _links?: _GetReferenceEntityRecords200OneAllOfLinks;
};
