/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Mathematic operation to convert the unit into the standard unit
 */
export type MeasureFamilyListAllOfFourUnitsItemConvert = { [key: string]: unknown };
