/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Measurement family labels for each locale
 */
export type MeasurementFamiliesGetList200Labels = {
  /** Measurement family label for the locale `localeCode` */
  localeCode?: string;
};
