/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { 413ErrorResponseOne } from './413ErrorResponseOne';

/**
 * Request Entity Too Large
 */
export type N413ErrorResponse = 413ErrorResponseOne;
