/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _PaginationLinks } from './_paginationLinks';

export interface Pagination {
  _links?: _PaginationLinks;
  /** Current page number */
  current_page?: number;
}
