/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

export type PaginationTypeParameter = typeof PaginationTypeParameter[keyof typeof PaginationTypeParameter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaginationTypeParameter = {
  page: 'page',
  search_after: 'search_after',
} as const;
