/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchMeasurementFamiliesBodyItemUnitsUnitCodeConvertFromStandardItem } from './patchMeasurementFamiliesBodyItemUnitsUnitCodeConvertFromStandardItem';
import type { PatchMeasurementFamiliesBodyItemUnitsUnitCodeLabels } from './patchMeasurementFamiliesBodyItemUnitsUnitCodeLabels';

export type PatchMeasurementFamiliesBodyItemUnitsUnitCode = {
  /** Measurement unit code. More details <a href='/concepts/target-market-settings.html#focus-on-the-units'>here</a>. */
  code?: string;
  /** Calculation to convert the unit from the standard unit. More details <a href='/concepts/target-market-settings.html#focus-on-the-units'>here</a>. */
  convert_from_standard?: PatchMeasurementFamiliesBodyItemUnitsUnitCodeConvertFromStandardItem[];
  /** Unit labels for each locale. More details <a href='/concepts/target-market-settings.html#focus-on-the-units'>here</a>. */
  labels?: PatchMeasurementFamiliesBodyItemUnitsUnitCodeLabels;
  /** Measurement unit symbol. More details <a href='/concepts/target-market-settings.html#focus-on-the-units'>here</a>. */
  symbol?: string;
};
