/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchAttributesBodyTableConfigurationItemDataType } from './patchAttributesBodyTableConfigurationItemDataType';
import type { PatchAttributesBodyTableConfigurationItemLabels } from './patchAttributesBodyTableConfigurationItemLabels';
import type { PatchAttributesBodyTableConfigurationItemValidations } from './patchAttributesBodyTableConfigurationItemValidations';

export type PatchAttributesBodyTableConfigurationItem = {
  /** Column code */
  code: string;
  /** Column data type */
  data_type: PatchAttributesBodyTableConfigurationItemDataType;
  /** Defines if the column should be entirely filled for the attribute to be considered complete */
  is_required_for_completeness?: boolean;
  /** Column labels for each locale */
  labels?: PatchAttributesBodyTableConfigurationItemLabels;
  /** User defined validation constraints on the cell content */
  validations?: PatchAttributesBodyTableConfigurationItemValidations;
};
