/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem } from './patchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem';
import type { PatchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem } from './patchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem';

export type PatchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCode = {
  /** Array of objects containing product model codes and quantities with which the product is in relation */
  product_models?: PatchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem[];
  /** Array of objects containing product uuids and quantities with which the product is in relation */
  products?: PatchProductsUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem[];
};
