/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchCategoriesCodeBodyValuesAttributeCodeAttributeUuidChannelCodeLocaleCodeItem } from './patchCategoriesCodeBodyValuesAttributeCodeAttributeUuidChannelCodeLocaleCodeItem';

/**
 * Attribute values
 */
export type PatchCategoriesCodeBodyValues = {
  'attributeCode|attributeUuid|channelCode|localeCode'?: PatchCategoriesCodeBodyValuesAttributeCodeAttributeUuidChannelCodeLocaleCodeItem[];
};
