/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Column data type
 */
export type PatchAttributesCodeBodyTableConfigurationItemDataType = typeof PatchAttributesCodeBodyTableConfigurationItemDataType[keyof typeof PatchAttributesCodeBodyTableConfigurationItemDataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchAttributesCodeBodyTableConfigurationItemDataType = {
  select: 'select',
  text: 'text',
  number: 'number',
  boolean: 'boolean',
} as const;
