/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchProductsUuidUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCode } from './patchProductsUuidUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCode';

/**
 * Several quantified associations related to products and/or product models, grouped by quantified association types (only available since the 5.0)
 */
export type PatchProductsUuidUuidBodyQuantifiedAssociations = {
  quantifiedAssociationTypeCode?: PatchProductsUuidUuidBodyQuantifiedAssociationsQuantifiedAssociationTypeCode;
};
