/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchAssetFamilyCodeBodyTransformationsItemOperations } from './patchAssetFamilyCodeBodyTransformationsItemOperations';
import type { PatchAssetFamilyCodeBodyTransformationsItemSource } from './patchAssetFamilyCodeBodyTransformationsItemSource';
import type { PatchAssetFamilyCodeBodyTransformationsItemTarget } from './patchAssetFamilyCodeBodyTransformationsItemTarget';

export type PatchAssetFamilyCodeBodyTransformationsItem = {
  /** The prefix that will be prepended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>. */
  filename_prefix?: string;
  /** The suffix that will be appended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>. */
  filename_suffix?: string;
  /** The name of the transformation */
  label: string;
  /** The transformations that should be applied to your source file to generate the target file. More details <a href='/concepts/asset-manager.html#transformation-operations'>here</a>. */
  operations: PatchAssetFamilyCodeBodyTransformationsItemOperations;
  /** The attribute value in which is stored the media file you want to use as the source file for your transformation. More details <a href='/concepts/asset-manager.html#source-file'>here</a>. */
  source: PatchAssetFamilyCodeBodyTransformationsItemSource;
  /** The attribute value in which the PIM will generate the new transformed file, aka the target file. More details <a href='/concepts/asset-manager.html#target-file'>here</a>. */
  target: PatchAssetFamilyCodeBodyTransformationsItemTarget;
};
