/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

export type PostTokenBody = {
  /** Always equal to "password" */
  grant_type: string;
  /** Your PIM password */
  password: string;
  /** Your PIM username */
  username: string;
};
