/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PostReferenceFilesLocaleCode201ErrorsItem } from './postReferenceFilesLocaleCode201ErrorsItem';

export type PostReferenceFilesLocaleCode201 = {
  errors?: PostReferenceFilesLocaleCode201ErrorsItem[];
  /** Message explaining the warning */
  message?: string;
};
