/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PostProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem } from './postProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem';
import type { PostProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem } from './postProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem';

export type PostProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCode = {
  /** Array of objects containing product model codes and quantities with which the product model is in relation */
  product_models?: PostProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem[];
  /** Array of objects containing product identifiers and quantities with which the product model is in relation */
  products?: PostProductModelsBodyQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem[];
};
