/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PostProductsUuidBodyAssociationsAssociationTypeCode } from './postProductsUuidBodyAssociationsAssociationTypeCode';

/**
 * Several associations related to groups, product models and/or other products, grouped by association types
 */
export type PostProductsUuidBodyAssociations = {
  associationTypeCode?: PostProductsUuidBodyAssociationsAssociationTypeCode;
};
