/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductUuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem } from './productUuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem';
import type { ProductUuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem } from './productUuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem';

export type ProductUuidQuantifiedAssociationsQuantifiedAssociationTypeCode = {
  /** Array of objects containing product model codes and quantities with which the product is in relation */
  product_models?: ProductUuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProductModelsItem[];
  /** Array of objects containing product uuids and quantities with which the product is in relation */
  products?: ProductUuidQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsItem[];
};
