/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductModelListAllOfFourAssociationsAssociationTypeCode } from './productModelListAllOfFourAssociationsAssociationTypeCode';

/**
 * Several associations related to groups, product and/or other product models, grouped by association types
 */
export type ProductModelListAllOfFourAssociations = {
  associationTypeCode?: ProductModelListAllOfFourAssociationsAssociationTypeCode;
};
