/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Warning: associations with quantities are not compatible with the published products. The response will always be empty.
 */
export type PublishedProductListAllOfFourQuantifiedAssociations = { [key: string]: unknown };
