/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { _PublishedProductListAllOfLinks } from './_publishedProductListAllOfLinks';

export type PublishedProductListAllOf = {
  _links?: _PublishedProductListAllOfLinks;
};
