/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */
import type { PublishedProductValuesAttributeCodeItemData } from './publishedProductValuesAttributeCodeItemData';

export type PublishedProductValuesAttributeCodeItem = {
  /** <a href='api-reference.html#Productuuid'>Product</a> value */
  data?: PublishedProductValuesAttributeCodeItemData;
  /** <a href='api-reference.html#Locale'>Locale</a> code of the product value */
  locale?: string;
  /** <a href='api-reference.html#Channel'>Channel</a> code of the product value */
  scope?: string;
};
