/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Return the count of items in the response. Be carefull with that, on a big catalog, it can decrease performance in a significative way
 */
export type WithCountParameter = boolean;
