/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Return information about category position into its category tree (only available since the 7.0 version)
 */
export type WithPositionParameter = boolean;
