/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Akeneo PIM REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Return labels of attribute options in the response. (Only available since the 5.0 version)
 */
export type WithAttributeOptionsParameter = boolean;
